### ISSUE TITLE
Parse error when combining exponents slashes

### ISSUE THREAD

**Issue by cmungall** [dalito/ucumvert#8]
```
> g.m2-1
No terminal matches '-' in the current parser context, at line 1 col 5

g.m2-1
    ^
Expected one of:
	* ANNOTATION
	* OPERATOR
```

This is fine according to the validator:

https://lhncbc.github.io/ucum-lhc/demo.html

<img width="476" alt="image" src="https://github.com/dalito/ucumvert/assets/50745/7262b7a6-b32c-4768-94d6-d66fe947d84e">

These all work:

- `m2`
- `g/m2`
- `g.m-1` (ok semantically doesn't make sense...)

So it's some combination

**Comment by dalito** [comment]
I am quite sure that `g.m2-1` is invalid. Let´s see if they reply to my issue. 

What were you expecting, `g.m2-1` = `g*m**(2**-1) = g.m-2`?

As I understand the spec minus is only allowed in exponents or factors and two exponents may not follow each other directly. 
´g.(m2)-1` or `(g.m2)-1` in are also invalid in ucumvert which is based on current UCUM spec v2.1.

Also interesting in UCUM-LHC validator:

* (g.m2)-1 (gram*[square meter]) is a valid unit expression. An exponent (-1) following a parenthesis is invalid as of revision 1.9 of the UCUM Specification. Did you mean g.m2-1?
* g.(m2)-1 (gram*[square meter]) is a valid unit expression. An exponent (-1) following a parenthesis is invalid as of revision 1.9 of the UCUM Specification. Did you mean m2-1?

**Comment by dalito** [comment]
NIH fixed their validator recently based on my bug report. So ucumvert was just stricter in validating standard compliance.
